/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.video.testui;

import com.sun.xml.internal.ws.util.StringUtils;
import com.video.testui.model.AccountStatus;
import com.video.testui.model.CheckAccountModel;
import lombok.Getter;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
@Getter
public class MainFrame extends javax.swing.JFrame {

    private DefaultTableModel dtm;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        try {
           
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            UIManager.put("PopupMenu.border", BorderFactory.createEmptyBorder());

            initComponents();

            this.dtm = (DefaultTableModel) this.table.getModel();

            initSpinner();
            initCheckBox();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public String[] getIds(){
        return this.txt_ids.getText().split("\n");
    }

    public void fillDataTable(int index, CheckAccountModel checkAccountModel) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                dtm.addRow(new Object[]{index, checkAccountModel.getID(), checkAccountModel.getStatus()});
            }
        });
    }

    public List<String> getIdsSelected(int colWannaSel){
        int[] rowsSelected = getSelectedRows();
        List<String> idsSelected = new ArrayList<>();
        for (Integer row : rowsSelected){
            String status = this.dtm.getValueAt(row, 2).toString();
            if (status.equals(AccountStatus.LIVE.toString())){
                idsSelected.add(
                        this.dtm.getValueAt(row, colWannaSel).toString()
                );
            }
        }
        return idsSelected;
    }

    public void setIdsSelected(List<String> idsSelected){
        this.txt_ids_selected.setText(
                String.join("\n", idsSelected)
        );
    }

    public int[] getSelectedRows(){
        return this.table.getSelectedRows();
    }

    private void initSpinner(){
        ((JSpinner.DefaultEditor) (this.spinner_test).getEditor()).getTextField().addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
            }

            @Override
            public void focusLost(FocusEvent e) {
                try {
                    spinner_test.commitEdit();
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(MainFrame.this, "Value invalid!!!", "Error!", 0);
                }
            }
        });
    }

    private void initCheckBox(){
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(this.cb_nam);
        buttonGroup.add(this.cb_nu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_ids = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btn_check = new javax.swing.JButton();
        btn_get_id_selected = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_ids_selected = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        spinner_test = new javax.swing.JSpinner();
        btn_get_spinner_val = new javax.swing.JButton();
        cb_nam = new javax.swing.JCheckBox();
        cb_nu = new javax.swing.JCheckBox();
        btn_check_gt = new javax.swing.JButton();
        toggle = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Main Frame", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nhập IDs");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 102, 28));

        txt_ids.setColumns(20);
        txt_ids.setRows(5);
        jScrollPane1.setViewportView(txt_ids);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 336, 347));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "ID", "Status"
            }
        ));
        jScrollPane2.setViewportView(table);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 50, 374, 347));

        jLabel2.setText("Danh sách ID");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 11, 102, 28));

        btn_check.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_check.setText("Start Check");
        btn_check.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(btn_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 415, 240, 55));

        btn_get_id_selected.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btn_get_id_selected.setText("Get ID Selected");
        btn_get_id_selected.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(btn_get_id_selected, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 170, 55));

        txt_ids_selected.setColumns(20);
        txt_ids_selected.setRows(5);
        jScrollPane3.setViewportView(txt_ids_selected);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 50, 234, 347));

        jLabel3.setText("IDs Selected");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 11, 102, 28));

        spinner_test.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel3.add(spinner_test, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 100, 50));

        btn_get_spinner_val.setText("Get Value Spinner");
        jPanel3.add(btn_get_spinner_val, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, 50));

        cb_nam.setText("Male");
        jPanel3.add(cb_nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 410, -1, -1));

        cb_nu.setText("Female");
        jPanel3.add(cb_nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 440, -1, -1));

        btn_check_gt.setText("Check Gioi Tinh");
        jPanel3.add(btn_check_gt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, 110, 50));

        toggle.setText("Check Nam");
        jPanel3.add(toggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, -1, 50));

        jTabbedPane1.addTab("Check Valid User Facebook", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_check;
    private javax.swing.JButton btn_check_gt;
    private javax.swing.JButton btn_get_id_selected;
    private javax.swing.JButton btn_get_spinner_val;
    private javax.swing.JCheckBox cb_nam;
    private javax.swing.JCheckBox cb_nu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner spinner_test;
    private javax.swing.JTable table;
    private javax.swing.JToggleButton toggle;
    private javax.swing.JTextArea txt_ids;
    private javax.swing.JTextArea txt_ids_selected;
    // End of variables declaration//GEN-END:variables
}
